repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-added-large-files

  - id: trailing-whitespace
    exclude: Generated
  - id: end-of-file-fixer
    exclude: Generated

  - id: check-case-conflict
  - id: check-json
  - id: check-yaml
  - id: check-symlinks
  - id: check-merge-conflict
  - id: check-toml
  - id: check-xml
  - id: check-yaml

  - id: double-quote-string-fixer

  - id: detect-private-key

  - id: no-commit-to-branch
    args: ['--pattern', '^(?!((feature|hotfix)\/PDM-[a-zA-Z0-9\-]+)$).*']

- repo: https://github.com/milin/giticket
  rev: v1.0
  hooks:
  - id:  giticket
    args: ['--regex=[^/][A-Z][A-Z0-9]+-.*[0-9]', '--format=[{ticket}] {commit_msg}', '--mode=regex_match']
