coverage_service: cobertura_xml
xcodeproj: Kaidee.xcodeproj
workspace: Kaidee.xcworkspace
scheme: Kaidee
configuration: Debug
output_directory: fastlane/test_output/slather
ignore:
  - Pods/*
  - Carthage/*
